# Generated by Django 5.2.7 on 2025-11-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_comment_image_alter_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='update',
            new_name='update_at',
        ),
    ]
