# Generated by Django 5.2.7 on 2025-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_remove_ticket_image_user_image_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/'),
        ),
    ]
