# Generated by Django 5.2.7 on 2025-11-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_remove_comment_image_comment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
