# Generated by Django 5.2.7 on 2025-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_rename_update_ticket_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('progress', 'progress'), ('solved', 'solved'), ('closed', 'closed')], default='open', max_length=20),
        ),
    ]
